//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.19 at 09:29:27 DU CET 
//


package com.aionemu.gameserver.model.templates;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.aionemu.gameserver.model.templates.quest.CollectItems;
import com.aionemu.gameserver.model.templates.quest.FinishedQuestConds;
import com.aionemu.gameserver.model.templates.quest.QuestDrop;
import com.aionemu.gameserver.model.templates.quest.Rewards;


/**
 * <p>Java class for QuestTemplate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuestTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="drops" type="{}QuestDrop" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="collect_items" type="{}CollectItems"/>
 *         &lt;element name="rewards" type="{}Rewards" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="finished_quest_conds" type="{}FinishedQuestConds"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minlevel_permitted" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="max_repeat_count" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cannot_share" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cannot_giveup" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="f_mission" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="race_permitted" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuestTemplate", propOrder = {
    "drops",
    "collectItems",
    "rewards",
    "finishedQuestConds"
})
public class QuestTemplate {

    protected List<QuestDrop> drops;
    @XmlElement(name = "collect_items", required = true)
    protected CollectItems collectItems;
    protected List<Rewards> rewards;
    @XmlElement(name = "finished_quest_conds", required = true)
    protected FinishedQuestConds finishedQuestConds;
    @XmlAttribute
    protected Integer id;
    @XmlAttribute
    protected String name;
    @XmlAttribute(name = "minlevel_permitted")
    protected Integer minlevelPermitted;
    @XmlAttribute(name = "max_repeat_count")
    protected Integer maxRepeatCount;
    @XmlAttribute(name = "cannot_share")
    protected Integer cannotShare;
    @XmlAttribute(name = "cannot_giveup")
    protected Integer cannotGiveup;
    @XmlAttribute(name = "f_mission")
    protected Integer fMission;
    @XmlAttribute(name = "race_permitted")
    protected String racePermitted;

    /**
     * Gets the value of the drops property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drops property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrops().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QuestDrop }
     * 
     * 
     */
    public List<QuestDrop> getDrops() {
        if (drops == null) {
            drops = new ArrayList<QuestDrop>();
        }
        return this.drops;
    }

    /**
     * Gets the value of the collectItems property.
     * 
     * @return
     *     possible object is
     *     {@link CollectItems }
     *     
     */
    public CollectItems getCollectItems() {
        return collectItems;
    }

    /**
     * Gets the value of the rewards property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rewards property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRewards().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rewards }
     * 
     * 
     */
    public List<Rewards> getRewards() {
        if (rewards == null) {
            rewards = new ArrayList<Rewards>();
        }
        return this.rewards;
    }

    /**
     * Gets the value of the finishedQuestConds property.
     * 
     * @return
     *     possible object is
     *     {@link FinishedQuestConds }
     *     
     */
    public FinishedQuestConds getFinishedQuestConds() {
        return finishedQuestConds;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Gets the value of the minlevelPermitted property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinlevelPermitted() {
        return minlevelPermitted;
    }
    
    /**
     * Gets the value of the maxRepeatCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxRepeatCount() {
        return maxRepeatCount;
    }

    /**
     * Gets the value of the cannotShare property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCannotShare() {
        return cannotShare;
    }

    /**
     * Gets the value of the cannotGiveup property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCannotGiveup() {
        return cannotGiveup;
    }

    /**
     * Gets the value of the fMission property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFMission() {
        return fMission;
    }

    /**
     * Gets the value of the racePermitted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRacePermitted() {
        return racePermitted;
    }

}
