//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.17 at 08:41:03 DU CET 
//


package com.aionemu.gameserver.dataholders;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.aionemu.gameserver.model.templates.QuestTemplate;


/**
 * <p>Java class for QuestsTemplates complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuestsTemplates">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="quest" type="{}QuestTemplate" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "quests")
public class QuestsData {

    @XmlElement(name = "quest", required = true)
    protected List<QuestTemplate> questsData;
    private Map<Integer, QuestTemplate>	questData	= new HashMap<Integer, QuestTemplate>();
    
	void afterUnmarshal(Unmarshaller u, Object parent)
	{
		for(QuestTemplate quest: questsData)
		{
			questData.put(quest.getId(), quest);
		}
		questsData.clear();
		questsData = null;
	}

	public QuestTemplate getQuestById(int id)
	{
		return questData.get(id);
	}
   
	public int size()
	{
		return questData.size();
	}
}
