//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 03:41:14 DU CET 
//


package com.aionemu.gameserver.model.templates.quest;


import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * @author MrPoke
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rewards", propOrder = {
    "rewardItem"
})
public class Rewards {

    @XmlElement(name = "reward_item")
    protected List<RewardItem> rewardItem;
    @XmlAttribute(name = "reward_id")
    protected Integer rewardId;
    @XmlAttribute
    protected Integer gold;
    @XmlAttribute
    protected Integer exp;
    @XmlAttribute(name = "reward_abyss_point")
    protected Integer rewardAbyssPoint;
    @XmlAttribute
    protected String title;

    public List<RewardItem> getRewardItem() {
        if (rewardItem == null) {
            rewardItem = new ArrayList<RewardItem>();
        }
        return this.rewardItem;
    }
    /**
     * Gets the value of the rewardId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRewardId() {
        return rewardId;
    }

    /**
     * Gets the value of the gold property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGold() {
        return gold;
    }

    /**
     * Gets the value of the exp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * Gets the value of the rewardAbyssPoint property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRewardAbyssPoint() {
        return rewardAbyssPoint;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

}