//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.19 at 09:29:27 DU CET 
//


package com.aionemu.gameserver.model.templates.quest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Rewards complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rewards">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="reward_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="gold" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="exp" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="reward_abyss_point" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rewards")
public class Rewards {

    @XmlAttribute(name = "reward_id")
    protected Integer rewardId;
    @XmlAttribute
    protected Integer gold;
    @XmlAttribute
    protected Integer exp;
    @XmlAttribute(name = "reward_abyss_point")
    protected Integer rewardAbyssPoint;
    @XmlAttribute
    protected String title;

    /**
     * Gets the value of the rewardId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRewardId() {
        return rewardId;
    }

    /**
     * Gets the value of the gold property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGold() {
        return gold;
    }

    /**
     * Gets the value of the exp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * Gets the value of the rewardAbyssPoint property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRewardAbyssPoint() {
        return rewardAbyssPoint;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

}
