//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.12 at 04:17:49 DU CET 
//


package com.aionemu.gameserver.questEngine.operations;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

import com.aionemu.gameserver.questEngine.model.QuestEnv;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuestOperations", propOrder = {
    "questOperations"
})
public class QuestOperations {

    @XmlElements({
        @XmlElement(name = "npc_dialog", type = NpcDialogOperation.class),
        @XmlElement(name = "give_exp", type = GiveExpOperation.class),
        @XmlElement(name = "take_item", type = TakeItemOperation.class),
        @XmlElement(name = "start_quest", type = StartQuestOperation.class),
        @XmlElement(name = "incrase_quest_var", type = IncraseQuestVarOperation.class),
        @XmlElement(name = "give_item", type = GiveItemOperation.class),
        @XmlElement(name = "set_quest_status", type = SetQuestStatusOperation.class)
    })
    protected List<QuestOperation> questOperations;

    public List<QuestOperation> getQuestOperations() {
        if (questOperations == null) {
        	questOperations = new ArrayList<QuestOperation>();
        }
        return this.questOperations;
    }

	public void operate(QuestEnv env)
	{
		for (QuestOperation oper : questOperations)
		{
				oper.doOperate(env);
		}
	}
}
