//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.11 at 02:51:34 DU CET 
//


package com.aionemu.gameserver.questEngine.model;

import javax.xml.bind.annotation.XmlEnum;


@XmlEnum
public enum ConditionOperation {

    EQUAL,
    GREATER,
    GREATER_EQUAL,
    LESSER,
    LESSER_EQUAL,
    NOT_EQUAL,
    IN,
    NOT_IN;

    public String value() {
        return name();
    }

    public static ConditionOperation fromValue(String v) {
        return valueOf(v);
    }

}
